### ISSUE TITLE
where can i download IACC.3 dataset？

### ISSUE THREAD

**Issue by alanMachineLeraning** [soCzech/TransNetV2#15]
where can i download IACC.3 dataset？

**Comment by soCzech** [comment]
You have to mail TRECVid, it is not publicly downloadable. But you can use any other dataset.

**Comment by alanMachineLeraning** [comment]
There are only 10 videos in the data set RAIDataset, so is there too little as a verification set for the paper?

**Comment by soCzech** [comment]
Stop spamming the issuues!!! Read the paper.
