### ISSUE TITLE
Could you please provide the usage of trainning code?

### ISSUE THREAD

**Issue by mohhao** [soCzech/TransNetV2#18]
Thanks for your great work,

Could you please provide the usage of trainning code with my own data

I want to detect gradual changes only，should I label one frame or multiple frames？

**Comment by soCzech** [comment]
> Could you please provide the usage of trainning code with my own data

As mentioned in README.md, you need to create the dataset first, then just edit the config file with correct paths and run `python training.py ../configs/transnetv2.gin`.

> I want to detect gradual changes only，should I label one frame or multiple frames？

Read https://arxiv.org/abs/2008.04838 or https://github.com/soCzech/MasterThesis/blob/main/Thesis.pdf what is the output of the network and how it is trained. The network uses both single-frame and multi-frame annotations but single-frame annotations may be good enough.
