### ISSUE TITLE
the output frame index is discontinuous

### ISSUE THREAD

**Issue by pandababyer** [soCzech/TransNetV2#20]
Hello, thank you for sharing the great work. when I test it with my own video, I find there are some discontinuous in the frame index like this.
![image](https://user-images.githubusercontent.com/24407543/109748742-54461000-7c14-11eb-8bd2-8f2fc776e357.png)

**Comment by soCzech** [comment]
Yes, it can be. You can take average of the boundaries if it is not desired.
