### ISSUE TITLE
How to get synthesis dataset 

### ISSUE THREAD

**Issue by zhanghaoxin1994** [soCzech/TransNetV2#21]
Hi, 
in paper, you mentioned that the synthesis data is used and boost performance. But, I didn't find the code to render transitions. 
Could you please provide the code to render transitions.

**Comment by soCzech** [comment]
Code to render transitions is here: https://github.com/soCzech/TransNetV2/blob/master/training/input_processing.py#L240
It is called from: https://github.com/soCzech/TransNetV2/blob/master/training/input_processing.py#L22-L23

**Comment by zhanghaoxin1994** [comment]
Thanks!
