### ISSUE TITLE
Command-line for shots detection and split in tensorflow or pytorch

### ISSUE THREAD

**Issue by Tortoise17** [soCzech/TransNetV2#27]
I am impressed with this tool. 
I want to ask the command line for 

`mp4` to `shots splitting` and 
`mp4` to `shots detection `
using the tool. 

If you can help.

**Comment by soCzech** [comment]
There is a cli tool.
See https://github.com/soCzech/TransNetV2/tree/master/inference#simple-usage.

Just install and use:
```
transnetv2_predict /path/to/video.mp4
```
