### ISSUE TITLE
error :  Pytorch inference 

### ISSUE THREAD

**Issue by textcunma** [soCzech/TransNetV2#28]
I try to inference with Pytorch.
Tensorflow 2.1 is not available now.
So, I installed tensorflow 2.7 and run programs.
Then I got the following error.

tensorflow.python.framework.errors_impl.OpError: not an sstable (bad magic number)

**Comment by soCzech** [comment]
It is not true. You can still get tensorflow 2.1.
See https://www.tensorflow.org/install/source#linux
Also, you can always build it from source or probably google a way how to read old model files.
