### ISSUE TITLE
path to scenes gt for -mapping in create_train_dataset

### ISSUE THREAD

**Issue by jeannedionisi** [soCzech/TransNetV2#29]
Hi,
First of all, thank you very much for this work.
I have a question that may be a bit silly, but I couldn't find an answer. Indeed, I would like to run the code corresponding to create_train_dataset [here](TransNetV2/training/create_dataset.py) , however I can't understand how to fill the mapping_fn parameter : could you tell me what is /path/to/scenes/gt please ? :) I really don't have any idea which file to put...

**Comment by soCzech** [comment]
It is the file with ground truth for a given video.
It is created e.g. here https://github.com/soCzech/TransNetV2/blob/master/training/consolidate_datasets.py#L206.

**Comment by jeannedionisi** [comment]
Thank you for your answer

**Comment by SIAK-q** [comment]
excuse me, have you re-implemented this network? could you please tell me how to solve this problem ? tensorflow.python.framework.errors_impl.InvalidArgumentError: Exception encountered when calling layer "bn" (type BatchNormalization).

input must be 4-dimensional[1,100,27,48,64] [Op:FusedBatchNormV3]

Call arguments received by layer "bn" (type BatchNormalization):
  • inputs=tf.Tensor(shape=(1, 100, 27, 48, 64), dtype=float32)
  • training=False
thank you very much
