### ISSUE TITLE
Can I get pretrained weights (.h5) file?

### ISSUE THREAD

**Issue by hairzooc** [soCzech/TransNetV2#3]
I've tested inference by using pb file you provided. It worked well. Thanks for the repo :)
And then I tried to run evaluation code but couldn't run 'cause the format of model is different.
Can I get pretrained weights (.h5) file for my research?

**Comment by soCzech** [comment]
Hi,
The `evaluate.py` expects you have trained the network yourself and you have the datasets in the correct training/validation format. The training script itself creates the `.hd5` weights.

To run evaluation on your data with the provided pre-trained model, I suggest the following taken from [inference/README.md](https://github.com/soCzech/TransNetV2/blob/master/inference/README.md#advanced-usage):
```
from transnetv2 import TransNetV2

# location of learned weights is automatically inferred
# add argument model_dir="/path/to/transnetv2-weights/" to TransNetV2() if it fails
model = TransNetV2()
video_frames, single_frame_predictions, all_frame_predictions = \
    model.predict_video("video.mp4")
```
Then load ground truth and compute metrics as taken from [evaluate.py](https://github.com/soCzech/TransNetV2/blob/master/training/evaluate.py#L85):
```
gt_scenes = np.loadtxt("video_gt.txt", dtype=np.int32, ndmin=2)

_, _, _, (tp, fp, fn), fp_mistakes, fn_mistakes = metrics_utils.evaluate_scenes(
    gt_scenes, metrics_utils.predictions_to_scenes((single_frame_predictions >= args.thr).astype(np.uint8)),
    return_mistakes=True)
```

Be sure your ground truth matches the expected format (e.g. it is not shifted by one or any other +1/-1 error) of [metrics_utils.evaluate_scenes](https://github.com/soCzech/TransNetV2/blob/master/training/metrics_utils.py#L26).

Is this solution ok for you?
