### ISSUE TITLE
What's the difference between the single_frame_predictions and all_frame_predictions?

### ISSUE THREAD

**Issue by applepieiris** [soCzech/TransNetV2#33]
`video_frames, single_frame_predictions, all_frame_predictions = \
    model.predict_video("test.mp4")`
I see in function `def predictions_to_scenes()`, it use the single frame predictions. The single frame predictions has the same shape with all_frame_predictions. We have already predict the frame is whether or not the shot boundry, Why we also want to know the all keyframes predcitions ? is it same?

Thank you for your contribution!

**Comment by soCzech** [comment]
See the paper for details ([arxiv.org/abs/2008.04838](https://arxiv.org/abs/2008.04838)).
But you can safely use only `single_frame_predictions` and discard `all_frame_predictions`.
