### ISSUE TITLE
one_hot vs many_hot

### ISSUE THREAD

**Issue by mohamad-hasan-sohan-ajini** [soCzech/TransNetV2#35]
Hey

In the `create_dataset.py`, there is a function named `scenes2zero_one_representation`. It returns two values, which based on your paper, related to the networks heads. In the implementation, they are called `one_hot` and `many_hot`.
I run the function for 100,000 times with different `scenes` sequences (that are generated randomly), and in all cases the returned values for both items were the same! I'm wondering if there is a point to set different names for these values? Or maybe there is a subtle difference I wasn't able to spot.

BTW, here is the code I tested the function with:

```
import numpy as np

from create_dataset import scenes2zero_one_representation

# create some random sequences
sequences, max_len = [], []
for num_seq in range(4):
    cursor = 0
    sequences.append([])
    for i in range(np.random.randint(10, 15)):
        run_len = np.random.randint(1, 100)
        sequences[-1].append([cursor, cursor + run_len])
        cursor += run_len + 1
    max_len.append(cursor)

# get result of the function
results = [scenes2zero_one_representation(s, m) for s, m in zip(sequences, max_len)]

# check if one_hot and many_hot vectors are different
if all([all(result[0] == result[1]) for result in results]):
    print('All values are the same!')
else:
    print('There is some difference.')
```

Regards

**Comment by soCzech** [comment]
Because the difference is when the scenes are not adjacent only (e.g. `[(0,4),(7,10)]`).
This can be the case of long dissolve transitions where frames in the middle of the transition do not belong to any scene.
