### ISSUE TITLE
About weight download

### ISSUE THREAD

**Issue by Scr-w** [soCzech/TransNetV2#36]
Is there a link where I can manually download the weight, because this weight always times out when my server pulls it. I look forward to hearing from you soon. Thank you very much.

**Comment by soCzech** [comment]
You can open the file at github.com and click "download".
Or use "raw" link, e.g. https://github.com/soCzech/TransNetV2/raw/master/inference/transnetv2-weights/variables/variables.data-00000-of-00001

**Comment by Scr-w** [comment]
Thank you for your reply. I found that two files variables.data-00000-of-00001 and saved_model.pb can be downloaded from folder transnetv2-weights. May I ask which one is the weight that can be used for testing. I look forward to hearing from you soon. Thank you very much.

**Comment by soCzech** [comment]
You need the whole directory with all the files.

**Comment by Scr-w** [comment]
Thank you very much for your reply. I have successfully completed the test. However, I found that the test can only test a single video. If I want to test 500 videos of Clipshots's test set, what should I do? And how can I evaluate my results?I look forward to hearing from you soon. Thank you very much.

**Comment by soCzech** [comment]
Here you have a set of steps to replicate the work: https://github.com/soCzech/TransNetV2#replicate-the-work

It is quite involved. You need to specify your question. "I can only test a single video, what should I do?" is utterly nonspecific.
