### ISSUE TITLE
Working with longer dissolves and 60fps videos?

### ISSUE THREAD

**Issue by fschvart** [soCzech/TransNetV2#40]
Hi Tomas,

Thank you so much for putting this code online. You guys did an excellent job on a model that is still considered a SOTA two years after it was posted!

I'm testing the model on a certain dataset and wanted to ask a few questions:

1. Are you able to share the .h5 file of your training? I want to try to finetune the model with my data and see if it can help me in getting better accuracy compared to training only with my dataset.
2. I'm working on 60fps and sometimes my dissolves tend to get to ~70 frames. What would you suggest I try to change if I want the model to augment with longer transitions? Or generally, would you suggest any chance for higher fps videos and transitions?

I'll really appreciate your help! Happy holidays!

**Comment by soCzech** [comment]
> Are you able to share the .h5 file of your training?

I no longer have it. You can convert the provided weights into h5 format or you can initialize the model layer by layer manually.

> What would you suggest I try to change if I want the model to augment with longer transitions?

Depends on the type of your transitions. You can always extract the video in approx. 30fps but I did not test that.
