### ISSUE TITLE
Error when training with IACC.3 dataset

### ISSUE THREAD

**Issue by subinok99** [soCzech/TransNetV2#41]
Hi,

I have successfully trained models on clipshot, RAI and BBC datasets. However, when I train the model on the IACC.3 dataset, I keep getting the error below,
P_REQUIRES failed at strided_slice_op.cc:108 : Invalid argument: slice index -1 of dimension 0 out of bounds

finally, the program ended with the error below.
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __inference_parse_train_sample_529}} {{function_node __inference_parse_train_sample_529}} slice index -1 of dimension 0 out of bounds.
[[{{node StatefulPartitionedCall/cond_3/then/_28/cond_3/PartitionedCall/strided_slice_9}}]]
[[StatefulPartitionedCall]] [Op:IteratorGetNext]

As instructed in the Readme (same as other datasets), after downloading the dataset, running 'consoliate_datasets.py', I created tfrecord with the 'train' version of 'create_dataset.py'. After that, a error arises when training.

can you help? What did I do wrong?

**Comment by SIAK-q** [comment]
Hello, can you download the files in the training and run the code? Can you please tell me if there are any special environment configurations that I need to pay attention to? Thank you.
