### ISSUE TITLE
Hyperparameters to tune?

### ISSUE THREAD

**Issue by fschvart** [soCzech/TransNetV2#42]
Hi,

Thanks for your amazing work!
I'm trying to use your code for a small project I'm working on, trying to detect scene endings in sports.
I have a decent size dataset, yet I can't get past the 80% F1 score.
I was wondering, what model hyperparameters would you suggest I try playing with? 

Thank you so much!

**Comment by fschvart** [comment]
Also, is there a way to track my validation F1 score during training?

**Comment by soCzech** [comment]
I would suggest focusing on the training data - the most important aspect. You may need to generate additional scenes artificially.
With respect to the validation metrics... feel free to update the code to track whatever you need:)
