### ISSUE TITLE
Importing a SavedModel with tf.saved_model.load requires a 'tags=' argument

### ISSUE THREAD

**Issue by leejiahe** [soCzech/TransNetV2#43]
Hi Tomas,

Awesome work you done here. Really appreciate the work done.

I had followed your instructions. I had setup a conda environment with python=3.6, tensorflow=2.1, pytorch=1.7.1, cudatoolkit=10.1.

This following error occurs 

`ValueError: Importing a SavedModel with tf.saved_model.load requires a 'tags=' argument if there is more than one MetaGraph. Got 'tags=None', but there are 0 MetaGraphs in the SavedModel with tag sets []. Pass a 'tags=' argument to load this SavedModel.`

when I tried to run

`python transnetv2.py some_video.mp4  `

as well as 

`python convert_weights.py`

I would love to hear from you on how to resolve this error.

Thank you again!

**Comment by soCzech** [comment]
This error is not related to TransNet; it is a TensorFlow error. Please make sure you really have the correct tensorflow version (try `tf.__version__`) and possibly consult the issue there.
