### ISSUE TITLE
OpError: not an sstable (bad magic number)

### ISSUE THREAD

**Issue by fantasycz** [soCzech/TransNetV2#5]
Hi, I tried to run the code as follows.

```
from transnetv2 import TransNetV2
model = TransNetV2()
```

For the first time, it shows parse error. I redownload the .pb model. And it show the OpError: not an sstable (bad magic number). Not sure what happened.

I also tried TransNet https://github.com/soCzech/TransNet. It works pretty well. And I like the visualization. I wonder could you please save the TransNet  and the weights as a .pb model? Since I want to use it with opencv and c++. Do you have any suggestions that how I can use it with opencv dnn? Suppose I have a video, what should I do to prepare the input for the model? Thank you very much.

**Comment by soCzech** [comment]
You have to provide more information:
1. The whole error with stack trace.
2. Version of your TensorFlow, Python, etc.

Have you checked the shas of the files (see Issue #1)?
Have you tried running it in docker container?

I do not plan on updating the original TransNet repo as this one is superior in perofrmance and sould be perfectly usable.

**Comment by fantasycz** [comment]
Hi Tomáš, the model works. The performance is amazing! It didn't work yesterday since the model file ddn't download well. 

I have a small question, in your code , it has

single_frame_predictions
all_frame_predictions.

What is the difference between these two? It seems these are both the probability of which a frame is end of a shot. Which one should I use?

BTW, could you please generate a frozen graph of the network? I think that will be helpful, since people who use c++ can also benefit from your excellent work. 

Thank you very much.

**Comment by soCzech** [comment]
> single_frame_predictions vs. all_frame_predictions

The difference is only for gradual transitions longer than one frame (e.g. dissolves). Then the single frame predictions predict only the middle frame of the transition whereas the all frame predictions predict all in-transition frames. Note the all frames predictions have not been used for evaluation. For more details, see [https://arxiv.org/abs/2008.04838](https://arxiv.org/abs/2008.04838).

> Could you please generate a frozen graph of the network?

Go ahead and generate whatever you need. You sould have all the information and data to convert the model and its weights to any format and any framework you need :)
