### ISSUE TITLE
OSError: Cannot parse file b'./saved_model.pb': Error parsing message.

### ISSUE THREAD

**Issue by LuyuProgram** [soCzech/TransNetV2#6]
after download all the file and trained model/weights manually,  I run the transnetv2.py in the inference, but raise an  exception:
OSError: Cannot parse file b'/path/to/saved_model.pb': Error parsing message.
the version of tensorflow is v2.1.0.

and I also run the docker command to build an image flow the readme.md in inference, but after I built the dockerfile successfully, I run the command in the readme.md to test a video, but still raise the same exception.
 
how can I solve this problem? thanks

**Comment by soCzech** [comment]
Can you provide sha256 of the file `/path/to/saved_model.pb`?
Do it by `sha256sum /path/to/saved_model.pb`.

Btw, look at issue #1.

**Comment by LuyuProgram** [comment]
I check the saved_model.pb carefully, and I found it's only 1.6M, smaller than 5.66M showed in the git. so I download it manually and tried again, finally it works!
thanks a lot for your help!
