### ISSUE TITLE
key-frame extraction

### ISSUE THREAD

**Issue by sakerbug** [soCzech/TransNetV2#8]
It is a great job. I could leave a question, how could I extract key-frames meanwhile extracting the caption of this frame, or how could the net get the time of key-frames, then find the caption?

**Comment by soCzech** [comment]
> How could I extract key-frames?

The network only detects shot boundaries. Extraction of key frames for each shot is up to you.

> Extracting the caption of this frame...

The network does not extract caption or anything else except the shot boundaries.
